name: Generar Imagen Docker en TAR
 
# Esto hace que se ejecute cada vez que subes un cambio a la rama 'main'
# o si decides ejecutarlo manualmente.
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
 
jobs:
  build-and-save:
    runs-on: ubuntu-latest # GitHub nos presta un servidor Ubuntu
    
    steps:
    # 1. Copia tus archivos al servidor de GitHub
    - name: Obtener el código
      uses: actions/checkout@v4
 
    # 2. Construye la imagen usando tu Dockerfile
    - name: Construir la imagen Docker
      run: docker build -t mi-web-docker
 
    # 3. Convierte la imagen a un archivo .tar
    - name: Guardar imagen como .tar
      run: docker save -o mi-web.tar mi-web-doker
 
    # 4. Sube el .tar para que puedas descargarlo
    - name: Subir archivo .tar listo para descargar
      uses: actions/upload-artifact@v4
      with:
        name: imagen-docker-tar
        path: mi-sitio-docker.tar
