name: Generar Imagen Docker en TAR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código
        uses: actions/checkout@v4

      - name: Construir imagen Docker
        run: docker build -t mi-web-docker .

      - name: Exportar imagen a TAR
        run: docker save mi-web-docker -o mi-web-docker.tar

      - name: Verificar archivo generado
        run: |
          ls -lh
          file mi-web-docker.tar

      - name: Subir TAR
        uses: actions/upload-artifact@v4
        with:
          name: mi-web-docker-tar
          path: mi-web-docker.tar
          if-no-files-found: error
